version: '3.8'

services:
    angular:
        build: ./frontend-angular
        container_name: angular
        ports:
            - "80:80"
        depends_on:
            - django
    django:
        build: ./backend-django-postgres
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend-django-postgres/:/usr/src/app/
        ports:
            - "8000:8000"
        depends_on: 
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres